background=#05030A
foreground=#D6CFFF

color0=#09060F
color1=#D65BAA
color2=#8BE9A8
color3=#C7A86D
color4=#5E3DB3
color5=#7A2FD6
color6=#7EE7F2
color7=#D8C8FF

color8=#4B3B66
color9=#FF79C6
color10=#A8FFB5
color11=#FFD580
color12=#9F8BFF
color13=#A86BFF
color14=#A8F5FF
color15=#FFFFFF

