background=#191622
foreground=#CDBBFF

color0=#22212C
color1=#FF5555
color2=#50FA7B
color3=#F1FA8C
color4=#9580FF
color5=#FF79C6
color6=#8BE9FD
color7=#E2D9FF

color8=#5A627F
color9=#FF7A7A
color10=#7CFF9C
color11=#FFF2A5
color12=#B89CFF
color13=#FF9BE5
color14=#A8F5FF
color15=#FFFFFF
